name: Generate Snake

on:
  schedule:
    # Executa todos os dias às 12h (UTC)
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  generate_snake:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ThiagoRAlmeida2
          output: dist/snake.svg
      - name: Push the Snake
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
